### PR TITLE
Don't obscure response error status in "read"

### PR DESCRIPTION
**Pull request by ef4**
If a `read` promise is rejected, the rejection reason is an `Error` object with the message `[object Object]`. It's not possible to get the underlying `reponse.status`.

This removes the `Error` and throws the response directly. Q supports rejection reasons that are not instances of `Error`.

### CODE REVIEW

**Comment by kriskowal** [comment]
Would you mind an alternative where the response object is a property of the thrown error?

**Comment by ef4** [comment]
How about this?

**Comment by kriskowal** [comment]
Yes. I’ll land this. Thanks.

**Comment by kriskowal** [comment]
I flattened all the changes into one commit and pushed. Thanks.

**Pull request closed without merging**
